export const TOGGLE_REQUEST_MODAL = 'TOGGLE_REQUEST_MODAL'
// export const INIT_NPS_CAMPSITES = 'INIT_NPS_CAMPSITES'

export const CAMPSITE_HAS_ERRORED = 'CAMPSITE_HAS_ERRORED'
export const CAMPSITE_IS_LOADING = 'CAMPSITE_IS_LOADING'
export const NPS_FETCH_SUCCESS = 'NPS_FETCH_SUCCESS'
